version: "3"
services:
  api:
    container_name: go-sse-api
    build:
      context: .
      dockerfile: ./cmd/api/Dockerfile
    ports:
      - 3000:3000

  redis:
    container_name: go-sse-redis
    image: redis:7.4.2
    volumes:
      - ./healthchecks:/healthchecks
    healthcheck:
      test: /healthchecks/redis.sh
      interval: 5s
    ports:
      - 6379:6379
    networks:
      - go-sse-backend

  mongo:
    container_name: go-sse-mongo
    image: mongo:7
    mem_limit: 5G
    mem_reservation: 2.5G
    restart: unless-stopped
    hostname: mongodb
    volumes:
      - ./.docker/mongodb-data:/data/db/
    environment:
      MONGO_REPLICA_SET_NAME: "rs0"
    ports:
      - "27018:27017"
    healthcheck:
      test: test $$(mongosh --quiet --eval "print(rs.status().ok); process.exit();") -eq 1
      interval: 10s
      start_period: 30s
    command: ["--replSet", "rs0", "--bind_ip_all"]
networks:
  go-sse-backend:
